apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaexpress-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaexpress-springboot
  template:
    metadata:
      name: javaexpress-springboot
      labels:
        app: javaexpress-springboot
    spec:
      containers:
      - name: springboot
        image: javaexpress/springboot-docker-demo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaexpress-springboot
spec:
  selector:
    app: javaexpress-springboot
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
